"""Transaction model for Family Wealth AI."""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Transaction:
    """Transaction model representing a buy/sell action."""

    tx_id: str
    user_id: str
    asset: str
    side: str  # BUY or SELL
    amount: float
    price: float
    total_thb: float
    source_app: str  # Dime or Binance
    date: str
    created_at: Optional[datetime] = None

    @classmethod
    def from_dict(cls, data: dict) -> "Transaction":
        """Create a Transaction from a dictionary."""
        return cls(
            tx_id=data.get("tx_id", ""),
            user_id=data.get("user_id", ""),
            asset=data.get("asset", ""),
            side=data.get("side", "BUY"),
            amount=float(data.get("amount", 0)),
            price=float(data.get("price", 0)),
            total_thb=float(data.get("total_thb", 0)),
            source_app=data.get("source_app", ""),
            date=data.get("date", ""),
            created_at=data.get("created_at"),
        )

    @classmethod
    def from_parsed_image(cls, parsed: dict, user_id: str) -> "Transaction":
        """Create a Transaction from Gemini parsed data."""
        amount = float(parsed.get("amount", 0))
        price = float(parsed.get("price", 0))
        total_thb = parsed.get("total_thb") or (amount * price)

        return cls(
            tx_id="",  # Will be generated by sheets service
            user_id=user_id,
            asset=parsed.get("asset", ""),
            side=parsed.get("side", "BUY").upper(),
            amount=amount,
            price=price,
            total_thb=float(total_thb),
            source_app=parsed.get("source_app", ""),
            date=parsed.get("date") or datetime.now().strftime("%Y-%m-%d"),
        )

    def to_dict(self) -> dict:
        """Convert Transaction to dictionary."""
        return {
            "tx_id": self.tx_id,
            "user_id": self.user_id,
            "asset": self.asset,
            "side": self.side,
            "amount": self.amount,
            "price": self.price,
            "total_thb": self.total_thb,
            "source_app": self.source_app,
            "date": self.date,
            "created_at": (
                self.created_at.isoformat() if self.created_at else None
            ),
        }
